// Defines the Arducom commands used for communicating with a Lucinda sketch

#define ARDUCOM_CMD_GET_CONFIG 1
#define ARDUCOM_CMD_DEFINE_CHANNEL 2
#define ARDUCOM_CMD_SET_GLOBAL_SPEED 3
#define ARDUCOM_CMD_SET_GLOBAL_BRIGHTNESS 4
#define ARDUCOM_CMD_ENABLE_CHANNEL 5
#define ARDUCOM_CMD_DISABLE_CHANNEL 6
#define ARDUCOM_CMD_SET_CHANNEL_PERIOD 7
#define ARDUCOM_CMD_SET_CHANNEL_PHASESHIFT 8
#define ARDUCOM_CMD_SET_CHANNEL_OFFSET 9
#define ARDUCOM_CMD_SET_CHANNEL_BRIGHTNESS 10
#define ARDUCOM_CMD_SET_CHANNEL_DUTYCYCLE 11
