// Defines the Arducom commands used for communicating with a Lucinda sketch

#define ARDUCOM_CMD_GET_CONFIG 1
#define ARDUCOM_CMD_DEFINE_CHANNEL 2
#define ARDUCOM_CMD_SET_SPEED 3
#define ARDUCOM_CMD_SET_GLOBAL_BRIGHTNESS 4
#define ARDUCOM_CMD_ENABLE_CHANNEL 5
#define ARDUCOM_CMD_DISABLE_CHANNEL 6
#define ARDUCOM_CMD_SET_OFFSET 7
#define ARDUCOM_CMD_SET_BRIGHTNESS 8
#define ARDUCOM_CMD_SET_DUTYCYCLE 9
#define ARDUCOM_CMD_SET_MACROCYCLE_LENGTH 10
#define ARDUCOM_CMD_SET_MACROCYCLE_COUNT 11
#define ARDUCOM_CMD_SET_MACROCYCLE_SHIFT 12
